// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxkQenkZUsDjTWI0j75FK4vZa9YmItXIU',
    appId: '1:408621199245:web:03aad985e036d7e8ced7c4',
    messagingSenderId: '408621199245',
    projectId: 'fir-crud-f9b1e',
    authDomain: 'fir-crud-f9b1e.firebaseapp.com',
    storageBucket: 'fir-crud-f9b1e.firebasestorage.app',
    measurementId: 'G-Z92CQHYMG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgMtX02rIWSazabTRiQM6dwt1GQx79Pls',
    appId: '1:408621199245:android:2c5a50128ad4fd5cced7c4',
    messagingSenderId: '408621199245',
    projectId: 'fir-crud-f9b1e',
    storageBucket: 'fir-crud-f9b1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM6_ulOU2AXaneJZuVFBYh3_VZoe0ha8M',
    appId: '1:408621199245:ios:9fcd1f180dfefc19ced7c4',
    messagingSenderId: '408621199245',
    projectId: 'fir-crud-f9b1e',
    storageBucket: 'fir-crud-f9b1e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM6_ulOU2AXaneJZuVFBYh3_VZoe0ha8M',
    appId: '1:408621199245:ios:9fcd1f180dfefc19ced7c4',
    messagingSenderId: '408621199245',
    projectId: 'fir-crud-f9b1e',
    storageBucket: 'fir-crud-f9b1e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxkQenkZUsDjTWI0j75FK4vZa9YmItXIU',
    appId: '1:408621199245:web:ac4c409f439e2012ced7c4',
    messagingSenderId: '408621199245',
    projectId: 'fir-crud-f9b1e',
    authDomain: 'fir-crud-f9b1e.firebaseapp.com',
    storageBucket: 'fir-crud-f9b1e.firebasestorage.app',
    measurementId: 'G-L5BTHHZ8CD',
  );
}
